---
- hosts: control01 #ubuntu-19.04
  become: yes # This means that all tasks will be executed with sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
   - name: "APT: Install aptitude package"
     apt:
        name: aptitude
- hosts: control02
  become: yes # This means that all tasks will be executed with sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: "Enable EPEL"
      yum:
        name: epel-release
        state: present
   #      force_apt_get: yes
   # - name: Update all packages to the latest version
   #   apt:
   #    upgrade: dist
   # - name: Run the equivalent of "apt-get update" as a separate step
   #   apt:
   #      update_cache: yes
   #   when:
   #     - ansible_distribution == "Ubuntu"
   #     - ansible_os_family == "Debian"
   # - name: Set repos http://neuro.debian.net/lists/xenial.us-ca.full
   #   get_url:
   #      url: http://neuro.debian.net/lists/xenial.us-ca.full
   #      dest: /etc/apt/sources.list.d/neurodebian.sources.list
   #      mode: 644
   #   when:
   #     - ansible_distribution == "Ubuntu"
   #     - ansible_os_family == "Debian"
   # - name: Receive repo keys hkp://pool.sks-keyservers.net:80
   #   command: apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
   #   when:
   #     - ansible_distribution == "Ubuntu"
   #     - ansible_os_family == "Debian"
   # - name: Check if key exists
   #   command: apt-key fingerprint 0xA5D32F012649A5A9
   #   when:
   #    - ansible_distribution == "Ubuntu"
   #    - ansible_os_family == "Debian"
   # - name: Run the equivalent of "apt-get update" as a separate step
   #   apt:
   #      update_cache: yes
   #   when:
   #     - ansible_distribution == "Ubuntu"
   #     - ansible_os_family == "Debian"
   # - name: Update repositories cache and install singularity packages
   #   apt:
   #      pkg: ['singularity-container','debootstrap', 'squashfs-tools']
   #      state: present
   #   when:
   #     - ansible_distribution == "Ubuntu"
   #     - ansible_os_family == "Debian"
   #
   # - name: Run some self tests for singularity install
   #   command: singularity selftest
   #   when:
   #     - ansible_distribution == "Ubuntu"
   #     - ansible_os_family == "Debian"
